app:
    resource: "@AppBundle/Controller/"
    type:     annotation


home:
    path:   /
    defaults: { _controller: AppBundle:Default:index }

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Main:contact }